### ISSUE TITLE
New Feature : Interface Change

### ISSUE THREAD

**Issue by supportreq** [owncloud/music#354]
Hi @MorrisJobke,

Can we change the UI of the music app from the boring Corporate to something like a soundcloud interface.. I am not a developer but can definitely help you with the UI.

Suggest..

**Comment by MorrisJobke** [comment]
cc @owncloud/designers

**Comment by enoch85** [comment]
Cool idea! :+1:

**Comment by jancborchardt** [comment]
I'd really prefer playlist support and aim for a layout more like Spotify: simple sidebar for playlists (could get album covers), and content as now with the songs in there.

But yeah, not 100% sure what you mean - can you supply a mockup?

**Comment by hmuus** [comment]
From my point of view there should by a choice for the user!
Opening the music app display an endless list of large icons sorted by somthing like
   ForEach artist or albumartist ForEach album ForEach title_of_artist_in_this_album Next Next Next
What's about small icons or even none?
What's about other sorting / recursion?
Whats about respecting other info like albumartist, cd, year, track? (cd / year are currently not in db)
Or a playlist?
I didn't dig into the code so far to be able to spot the files involved for the main list. This would be my starting point for modding. Any help appriciated. Same for cd / year to have them available.

**Comment by jancborchardt** [comment]
@hmuus that would mean we need to maintain all these layouts. It’s difficult enough to maintain the Music app by itself. If you want to get involved in the code, it would be awesome if you could take a look at the bugs: https://github.com/owncloud/music/issues?q=is%3Aopen+is%3Aissue+label%3ABug :)

**Comment by hmuus** [comment]
@jancborchardt got it, fair enough to get bugs closed first before starting additions .. i did take a look, but this would mean to install various versions of owncloud with various versions of music along with other software i.e. tomahawk or maybe even various browsers .. sorry, but I just have a single install for my friends and family .. so i'm going back and start to do
1 take care that cd numer and year are available in table album
 a db creation
 b music scan
2 try to make listing page skinnable

**Comment by jancborchardt** [comment]
@hmuus it would be cool if we could work towards a common goal. Having the year available sounds good. CD number as well, but please only if it’s there. Not have an empty row if there’s no CD number.

We most likely will not pull in »skinnability« of the app. If you want to improve the design, let’s please work on it together, and not on just the ability to relayout arbitrarily.

If you want to work on cool new stuff, I recommend the playlists feature. cc @vgezer @MorrisJobke

**Comment by hmuus** [comment]
@jancborchardt I don't understand 'cd only if there' .. either there is a field in the database -which, yes, can be emty- or there is no field and we won't get it in either case. pls clarify

**Comment by jancborchardt** [comment]
@hmuus I meant regarding the layout. There shouldn’t be an empty table column or something like that just to show the CD number for some few albums.

**Comment by hmuus** [comment]
@jancborchardt ok... found no tables by the way, just divs .. anyway .. some interesting:
```
<div class="artist-area ng-scope" ng-repeat="artist in artists | orderBy:'name'" ng-init="letter = artist.name.substr(0,1).toUpperCase()">
    <span class="ng-hide" id="1" ng-show="letterAvailable[letter]">A</span>
    <h1 class="ng-binding" ng-click="playArtist(artist)">Artist<img class="play svg" alt="Abspielen" src="/owncloud/apps/music/img/play-big.svg"></h1>
    <!-- ngRepeat: album in artist.albums | orderBy:'year' -->
    <div class="album-area ng-scope" ng-repeat="album in artist.albums | orderBy:'year'">
        <h2 ng-click="playAlbum(album)" title="Album ()">
            <div class="ng-binding">Album		<span ng-show="album.year" class="muted ng-binding ng-hide">()</span></div>
        </h2>
        <div style="background-color: rgb(115, 85, 246); color: rgb(255, 255, 255); font-weight: bold; text-align: center;" ng-click="playAlbum(album)" class="albumart" cover="" albumart="Album">A</div>
        <img ng-click="playAlbum(album)" class="play overlay svg" alt="Abspielen" src="/owncloud/apps/music/img/play-big.svg">
...
```
order by Year !  ng-show="album.year" ! seems to be in already .. will dig further ..

Another question: opening music from dashboard tries to load a bunch of coffee files and additional js files from 'myserver'/Users/devongovett/codecs/aurora.js/'various_sources' .. didn't figure out where this comes from .. can you help?

**Comment by jancborchardt** [comment]
@hmuus yeah, it’s ordered by newest album first I think. @MorrisJobke?

**Comment by hmuus** [comment]
@jancborchardt miracle is gone: devongovett has left some map files in the repo (he was involved in some activities on flac) .. deleted them and unloadable files disapear .. i read they will appear in debug mode only .. so .. maybe no issue at all, but the should be not in the repo anyway

**Comment by hmuus** [comment]
@MorrisJobke @jancborchardt 

helper.php first sql statement throws error each cron job:

SQLSTATE[HY000]: General error: 1093 You can't specify target table 'oc_music_albums' for update in FROM clause

proposal: replace by
```
CREATE TABLE IF NOT EXISTS `*PREFIX*music_albums_cleanup` AS 
SELECT `cover_file_id` FROM `*PREFIX*music_albums` LEFT JOIN `*PREFIX*filecache` ON `cover_file_id`=`fileid` WHERE `fileid` IS NULL

UPDATE `*PREFIX*music_albums` SET `cover_file_id` = NULL WHERE `cover_file_id` IS NOT NULL AND `cover_file_id` IN (SELECT `cover_file_id` FROM `*PREFIX*music_albums_cleanup`)

DROP TABLE `*PREFIX*music_albums_cleanup`
```
any concerns ?

**Comment by hmuus** [comment]
The complete file:
```
<?php

/**
 * ownCloud - Music app
 *
 * This file is licensed under the Affero General Public License version 3 or
 * later. See the COPYING file.
 *
 * @author Morris Jobke <hey@morrisjobke.de>
 * @copyright Morris Jobke 2014
 *
 * update 25.March 2015
 * hmuus
 */

namespace OCA\Music\Utility;

use \OCA\Music\AppFramework\Core\Db;


class Helper {

	private $db;

	public function __construct(Db $db){
		$this->db = $db;
	}

	/**
	 * Removes orphaned data from the database
	 */
	public function cleanUp() {
		$sqls = array(
/*SQLSTATE[HY000]: General error: 1093 You can't specify target table for update in FROM clause
			'UPDATE `*PREFIX*music_albums` SET `cover_file_id` = NULL WHERE `cover_file_id` IS NOT NULL AND `cover_file_id` IN (SELECT `cover_file_id` FROM `*PREFIX*music_albums` LEFT JOIN `*PREFIX*filecache` ON `cover_file_id`=`fileid` WHERE `fileid` IS NULL);',
*/			'CREATE TABLE IF NOT EXISTS `*PREFIX*music_albums_cleanup` AS 
SELECT `cover_file_id` FROM `*PREFIX*music_albums` LEFT JOIN `*PREFIX*filecache` ON `cover_file_id`=`fileid` WHERE `fileid` IS NULL;',
			'UPDATE `*PREFIX*music_albums` SET `cover_file_id` = NULL WHERE `cover_file_id` IS NOT NULL AND `cover_file_id` IN (SELECT `cover_file_id` FROM `*PREFIX*music_albums_cleanup`);',
			'DROP TABLE `*PREFIX*music_albums_cleanup`;',
/*SQLSTATE[HY000]: General error: 1093 You can't specify target table for update in FROM clause
			'DELETE FROM `*PREFIX*music_tracks` WHERE `file_id` IN (SELECT `file_id` FROM `*PREFIX*music_tracks` LEFT JOIN `*PREFIX*filecache` ON `file_id`=`fileid` WHERE `fileid` IS NULL);',
*/			'CREATE TABLE IF NOT EXISTS `*PREFIX*music_tracks_cleanup` AS 
SELECT `file_id` FROM `*PREFIX*music_tracks` LEFT JOIN `*PREFIX*filecache` ON `file_id`=`fileid` WHERE `fileid` IS NULL;',
			'DELETE FROM `*PREFIX*music_tracks` WHERE `file_id` IN (SELECT `file_id` FROM `*PREFIX*music_tracks_cleanup`);',
			'DROP TABLE `*PREFIX*music_tracks_cleanup`;',
			'DELETE FROM `*PREFIX*music_albums` WHERE `id` NOT IN (SELECT `album_id` FROM `*PREFIX*music_tracks` GROUP BY `album_id`);',
			'DELETE FROM `*PREFIX*music_album_artists` WHERE `album_id` NOT IN (SELECT `id` FROM `*PREFIX*music_albums` GROUP BY `id`);',
			'DELETE FROM `*PREFIX*music_artists` WHERE `id` NOT IN (SELECT `artist_id` FROM `*PREFIX*music_album_artists` GROUP BY `artist_id`);'
		);

		foreach ($sqls as $sql) {
			$query = $this->db->prepareQuery($sql);
			$query->execute();
		}
	}
}
```
No more errors in log

**Comment by jancborchardt** [comment]
@hmuus since this is very different from the original issue, can you open a new one? Thanks.

**Comment by hmuus** [comment]
done

**Comment by hmuus** [comment]
Ok.. I did a some research and understand that it will be extremly hard to have other sorting than existing. Throughout the complete app its everywhere sortetd by artist, then album, then track of this artist in that album. Fine for a collection of cds of various artists, but samplers or a loose collecting of various tracks are poorly supported as the resulting list will not allow a comfortable way to access them. Database is lacking in terms of having the cd number or the genre available. A simple list with sorting criteria as existing in owncloud's file app is not available. As soon music is installed shares are no longer working as it will kick you to the music page where this is not available (ok, when the app determine that this wouldn't work and kick me back, but just kick me there and the nleave me alone, no). So .. some basic features will be hard to reach with the current design. For the simple idea to have other sorting I would need to redesign a large portion of this app. This is too mush, I give up. I will now try to trick a bit by mp3 tagging (by the way: a tag editor in this app ..) and hope the result is bearable.

**Comment by paulijar** [comment]
I think it's time to close this old issue. A lot has changed in the Music web UI during the past six years although the basic concept of the albums view is still the same. Doing something totally different with the UI would be too much work for the benefit and with the development resources at hand. If anyone wants to suggest UI changes, then that should happen with smaller and more coherent feature requests.
