### ISSUE TITLE
Error while running background job: An exception occurred while executing 'UPDATE `oc_music_albums`

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/music#402]
### Steps to reproduce
Happens during cron's background job

### Expected behaviour
Do the job and complete it successfully

### Actual behaviour
Here's the log output

```
$ tail owncloud.log
{"reqId":"TkW6fALsXZnTNh7Nyjwk","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/var\/www\/owncloud\/apps\/contacts\/appinfo\/app.php#35","level":3,"time":"2015-07-16T04:15:01+00:00"}
{"reqId":"TkW6fALsXZnTNh7Nyjwk","remoteAddr":"","app":"no app in context","message":"Error while running background job: An exception occurred while executing 'UPDATE `oc_music_albums` SET `cover_file_id` = NULL WHERE `cover_file_id` IS NOT NULL AND `cover_file_id` IN (SELECT `cover_file_id` FROM `oc_music_albums` LEFT JOIN `oc_filecache` ON `cover_file_id`=`fileid` WHERE `fileid` IS NULL);':\n\nSQLSTATE[HY000]: General error: 1093 You can't specify target table 'oc_music_albums' for update in FROM clause","level":3,"time":"2015-07-16T04:15:07+00:00"}
{"reqId":"dw9vJKjH7y4iyXZZwjmh","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/var\/www\/owncloud\/apps\/contacts\/appinfo\/app.php#35","level":3,"time":"2015-07-16T04:30:01+00:00"}
{"reqId":"dw9vJKjH7y4iyXZZwjmh","remoteAddr":"","app":"no app in context","message":"Error while running background job: An exception occurred while executing 'UPDATE `oc_music_albums` SET `cover_file_id` = NULL WHERE `cover_file_id` IS NOT NULL AND `cover_file_id` IN (SELECT `cover_file_id` FROM `oc_music_albums` LEFT JOIN `oc_filecache` ON `cover_file_id`=`fileid` WHERE `fileid` IS NULL);':\n\nSQLSTATE[HY000]: General error: 1093 You can't specify target table 'oc_music_albums' for update in FROM clause","level":3,"time":"2015-07-16T04:30:17+00:00"}
{"reqId":"m6xFaKOPqusZ4vgJtQec","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/var\/www\/owncloud\/apps\/contacts\/appinfo\/app.php#35","level":3,"time":"2015-07-16T04:45:01+00:00"}
{"reqId":"m6xFaKOPqusZ4vgJtQec","remoteAddr":"","app":"no app in context","message":"Error while running background job: An exception occurred while executing 'UPDATE `oc_music_albums` SET `cover_file_id` = NULL WHERE `cover_file_id` IS NOT NULL AND `cover_file_id` IN (SELECT `cover_file_id` FROM `oc_music_albums` LEFT JOIN `oc_filecache` ON `cover_file_id`=`fileid` WHERE `fileid` IS NULL);':\n\nSQLSTATE[HY000]: General error: 1093 You can't specify target table 'oc_music_albums' for update in FROM clause","level":3,"time":"2015-07-16T04:45:06+00:00"}
{"reqId":"3ZS9Zfamm9oRVK7zS+Kq","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/var\/www\/owncloud\/apps\/contacts\/appinfo\/app.php#35","level":3,"time":"2015-07-16T05:00:01+00:00"}
{"reqId":"3ZS9Zfamm9oRVK7zS+Kq","remoteAddr":"","app":"no app in context","message":"Error while running background job: An exception occurred while executing 'UPDATE `oc_music_albums` SET `cover_file_id` = NULL WHERE `cover_file_id` IS NOT NULL AND `cover_file_id` IN (SELECT `cover_file_id` FROM `oc_music_albums` LEFT JOIN `oc_filecache` ON `cover_file_id`=`fileid` WHERE `fileid` IS NULL);':\n\nSQLSTATE[HY000]: General error: 1093 You can't specify target table 'oc_music_albums' for update in FROM clause","level":3,"time":"2015-07-16T05:00:14+00:00"}
{"reqId":"SmA241yzR9ICvQaOOYgf","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/var\/www\/owncloud\/apps\/contacts\/appinfo\/app.php#35","level":3,"time":"2015-07-16T05:15:02+00:00"}
{"reqId":"SmA241yzR9ICvQaOOYgf","remoteAddr":"","app":"no app in context","message":"Error while running background job: An exception occurred while executing 'UPDATE `oc_music_albums` SET `cover_file_id` = NULL WHERE `cover_file_id` IS NOT NULL AND `cover_file_id` IN (SELECT `cover_file_id` FROM `oc_music_albums` LEFT JOIN `oc_filecache` ON `cover_file_id`=`fileid` WHERE `fileid` IS NULL);':\n\nSQLSTATE[HY000]: General error: 1093 You can't specify target table 'oc_music_albums' for update in FROM clause","level":3,"time":"2015-07-16T05:15:06+00:00"}

```

### Server configuration

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty
```

```
$ uname -a      
Linux binarykitchen.com 3.12.27-xenU #1 SMP Thu Aug 28 23:13:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Web server:

```
$ nginx -v
nginx version: nginx/1.8.0
```

Database:

```
$ mysql --version
mysql  Ver 14.14 Distrib 5.5.43, for debian-linux-gnu (x86_64) using readline 6.3
```

PHP version:

```
$ php -v
PHP 5.5.27-1+deb.sury.org~trusty+1 (cli) (built: Jul 15 2015 12:14:44) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

ownCloud version:
ownCloud 8.1.0-3 (stable) 

Updated from an older ownCloud or fresh install:
Fresh install via apt-get

```
$ sudo -u www-data php ./occ app:list
Enabled:
 - activity: 2.0.1
 - bookmarks: 0.4
 - calendar: 0.7.1
 - contacts: 0.4.0.0
 - documents: 0.9.0
 - encryption: 1.0.0
 - external: 1.2
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - galleryplus: 12
 - mozilla_sync: 1.4
 - music: 0.3.5
 - provisioning_api: 0.2
 - storagecharts2: 2.6.1
 - tasks: 0.7.1
 - templateeditor: 0.1
 - videos: 1.0
Disabled:
 - files_external
 - files_trashbin
 - firstrunwizard
 - gallery
 - user_external
 - user_ldap
 - user_webdavauth
```

The content of config/config.php: (Without sensitive data)

```
$ cat config.php                                                                                                                                                                                       Â î‚²Â 1Â 
<?php
$CONFIG = array (
  'instanceid' => 'oc02ca513338',
  'passwordsalt' => 'xxx',
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'xxx',
  'installed' => true,
  'forcessl' => true,
  'loglevel' => 1,
  'logfile' => '/var/log/owncloud.log',
  'theme' => '',
  'maintenance' => false,
  'memcache.local' => '\OC\Memcache\APCu',
  'trusted_domains' => 
  array (
    0 => 'xxx',
  ),
  'mail_smtpmode' => 'smtp',
  'secret' => 'xxx',
  'forceSSLforSubdomains' => true,
  'mail_smtpsecure' => 'tls',
  'mail_smtphost' => '127.0.0.1',
  'mail_smtpport' => 'xxx',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'xxx',
  'mail_smtppassword' => 'xxx',
  'mail_smtpauthtype' => 'PLAIN',
);

```

Are you using external storage, if yes which one:
None

### Client configuration
Browser:
Firefox 40

Operating system:
Ubuntu 15.04

#### Web server error log

Plenty of those nginx entries:

```
2015/07/16 17:22:10 [error] 2041#0: *1726 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 203.84.135.120, server: cloud.binarykitchen.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock", host: "cloud.binarykitchen.com"
```

#### ownCloud log (data/owncloud.log)
N/A

#### Browser log
Irrelevant

**Comment by binarykitchen** [comment]
This problem is breaking my whole owncloud. Didn't happen before I enabled the apcu cache.

**Comment by MorrisJobke** [comment]
Seems to be an issue with contacts: https://github.com/owncloud/contacts/issues/972

Fix is in https://github.com/owncloud/contacts/pull/973

**Comment by MorrisJobke** [comment]
Other log entries are fixed with #372

**Comment by binarykitchen** [comment]
I am still seeing the above issues. When will these fixes be available via `apt-get`?

**Comment by MorrisJobke** [comment]
> I am still seeing the above issues. When will these fixes be available via apt-get?

`apt-get`? I don't think there are package for the music app of ownCloud :see_no_evil: 

Simply install 0.3.7 of the music app on you instance.

**Comment by binarykitchen** [comment]
How would you install it then? I cannot find it under the "Apps" tab
